language: php

 notifications:
   email:
     on_success: never
     on_failure: change

 branches:
   only:
     - develop

 php:
   - 5.3
   - 5.4
   - 5.5
   - 5.6

 env:
   - WP_VERSION=latest WP_MULTISITE=0
   - WP_VERSION=3.1.0 WP_MULTISITE=0
   - WP_VERSION=4.3.2 WP_MULTISITE=0

 matrix:
   include:
     - php: 5.3
       env: WP_VERSION=latest WP_MULTISITE=1
     - php: 5.4
       env: WP_VERSION=latest WP_MULTISITE=1
     - php: 5.5
       env: WP_VERSION=latest WP_MULTISITE=1
     - php: 5.6
       env: WP_VERSION=latest WP_MULTISITE=1

 before_script:
   - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

 script: phpunit